### ISSUE TITLE
Deposit PDF in repo?

### ISSUE THREAD

**Issue by davidlmobley** [dmzuckerman/Sampling-Uncertainty#26]
Any chance you guys would want to deposit the latest version of the PDF in the repo with commits? I just stumbled across this and would love to be able to see the PDF without having to compile. Typically what we do is just update the PDF with any commit which touches any of the content.

**Comment by agrossfield** [comment]
I had put it in the gitignore but I can edit it later today.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical School


On Nov 24, 2017, at 2:52 PM, David L. Mobley <notifications@github.com<mailto:notifications@github.com>> wrote:


Any chance you guys would want to deposit the latest version of the PDF in the repo with commits? I just stumbled across this and would love to be able to see the PDF without having to compile. Typically what we do is just update the PDF with any commit which touches any of the content.

-

**Comment by davidlmobley** [comment]
That would be great. I think for people wanting to see your latest version, this will be way easier than having them compile, especially if they've never used LaTeX before.

**Comment by dwsideriusNIST** [comment]
I updated the gitignore and uploaded a compiled main version.
