### ISSUE TITLE
Question about uncertainty propagation section

### ISSUE THREAD

**Issue by agrossfield** [dmzuckerman/Sampling-Uncertainty#3]
I understand making it clear that there are limitations to the use of the Taylor expansion approach (this is important and NOT obvious to many people!).

However, I don't see any reason why you couldn't directly estimate the uncertainty in dA via block averaging.  Why would averaging exp(-beta dU) in block be ok, but not taking the log of it?  I know it's not exactly the usual block averaging formula (which has the average as the last operation), but I can't think of a reason why it wouldn't work.  You compute dA using blocks of the data, and watch the variance change as the block change size.  If I'm missing something (which wouldn't surprise me), we need to explain it, because it's not obvious.  If by rare chance I'm right, we should change the section.

**Comment by ajschult** [comment]
To be clear, you're asking about computing something like ln<exp(-beta dU)> for each block?  The pathological case might serve as a good example of failure.  It could be that dU is consistently infinity for all samples in a block.  <exp(-beta dU)> is 0 and ln(0) is NaN.  Clearly, this cannot be used to compute an uncertainty.  Moving away from the pathological case,  ln<exp(-beta dU)> will tend to take extreme negative values in blocks where the perturbation does poorly; while that could be used, it would certainly throw off the uncertainty calculation.

**Comment by agrossfield** [comment]
That makes perfect sense, and should be added to the document.  I figured I must be missing something. :)

Alan

On Sep 25, 2017, at 9:39 AM, Andrew Schultz <notifications@github.com<mailto:notifications@github.com>> wrote:


To be clear, you're asking about computing something like ln<exp(-beta dU)> for each block? The pathological case might serve as a good example of failure. It could be that dU is consistently infinity for all samples in a block. <exp(-beta dU)> is 0 and ln(0) is NaN. Clearly, this cannot be used to compute an uncertainty. Moving away from the pathological case, ln<exp(-beta dU)> will tend to take extreme negative values in blocks where the perturbation does poorly; while that could be used, it would certainly throw off the uncertainty calculation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dmzuckerman_Sampling-2DUncertainty_issues_3-23issuecomment-2D331884102&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ehpm3hAuYU2UEuWwa1dXhHCVizqXPXAt2UZqc4EX_N4&s=lUcWyMOjhAOq9log-TKnhB4sDd2syMRB9Mk1LpDukLg&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM-5F-2D8pFj4J7D9LHUJTQuYQp5VX11k52lks5sl60rgaJpZM4PivGP&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ehpm3hAuYU2UEuWwa1dXhHCVizqXPXAt2UZqc4EX_N4&s=KgXpIfjlAI2cKi00P_oAlU4DLKRHOAOOvGADKuGV8pU&e=>.

___________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu

**Comment by ajschult** [comment]
I've added more text to explain why propagation of uncertainty is needed.

Thanks for the feedback!

**Comment by agrossfield** [comment]
I’m pleased — this mechanism seems to be working as designed!

Alan

On Sep 25, 2017, at 10:29 AM, Andrew Schultz <notifications@github.com<mailto:notifications@github.com>> wrote:


I've added more text to explain why propagation of uncertainty is needed.

Thanks for the feedback!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dmzuckerman_Sampling-2DUncertainty_issues_3-23issuecomment-2D331899362&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=c4GAbkpg4JxOOaMVDZPkYjVb5yEhASqjOdik8QjTUY4&s=7SkcgGwSCdos3VyJFM4keMSzd-6UIYH0gMmPTjVxfG0&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM-5F-2D8gYmANChmmmwXlz-5FLoImU2gEvNdYks5sl7jWgaJpZM4PivGP&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=c4GAbkpg4JxOOaMVDZPkYjVb5yEhASqjOdik8QjTUY4&s=mPOBoAbWhKYpN-JJWeSOzTspRb7ROhVwnqw9LzMxHk0&e=>.

___________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
