### ISSUE TITLE
Couple quick comments

### ISSUE THREAD

**Issue by davidlmobley** [dmzuckerman/Sampling-Uncertainty#34]
I'm scanning through this as I prepare a lecture, and happened to notice a couple things:
- one occurrence of "uncertainy" rather than "uncertainty"
- The checklist has this point, which is quite helpful: "This practice ethically questionable and, at a minimum, can significantly bias your conclusions. Use all of the available data unless there is an objective and compelling reason not to, e.g. the simulation setup was incorrect or a sampling metric indicated that the simulation was not equilibrated." However, I wonder if this should be slightly expanded to add the idea that, if you're discarding something due to bad sampling or poor equilibration, you should be applying the same analysis to ALL of your simulations. In my experience it's easy to closely scrutinize any simulations which give bad results, while ignoring simulations which give good results. If you, say, carefully check your "bad" simulations for equilibration/poor sampling but don't do the same for your "good" simulations you're also cherry-picking, and this could perhaps be made clearer.

**Comment by dwsideriusNIST** [comment]
Addressed in https://github.com/dmzuckerman/Sampling-Uncertainty/commit/a036057bc85bd013e632855e490ae14f93a667d7
