### ISSUE TITLE
PDF Rendering Issues

### ISSUE THREAD

**Issue by dwsideriusNIST** [dmzuckerman/Sampling-Uncertainty#37]
From a reviewer: "The pdf i received had substantial formatting issues. It appears that the letters "fi" often was reproduced as "!" and many other such curious formatting issues appeared. For example, there where "squares" where letters should be and "Definitions" has an á with no fi. I encourage the editors / authors make sure these formatting issues do not appear in the final version."

Can anyone confirm this issue? The PDF opens fine in three viewers on my Linux PC and in two viewers on my Mac.

**Comment by agrossfield** [comment]
I also can't reproduce the problem.  I wonder if something went wrong either with the journal's translation, or if there's something funky in the reviewer's set up.  We should probably get someone to check on Windows though, since I too only checked on Linux and Mac.

**Comment by dwsideriusNIST** [comment]
Due to our inability to reproduce the issue, I'm going to blame it on old PDF software and/or a really terrible font set on the reviewer's PC. Let's throw it back to the editors, suggest they ask the reviewer about his PDF viewer configuration, then deal with it if there's something we can do in the rendering step. Closed for now.
