### ISSUE TITLE
N vs N-1

### ISSUE THREAD

**Issue by dwsideriusNIST** [dmzuckerman/Sampling-Uncertainty#38]
From a reviewer: For eqn 8, the authors may wish to discuss when n and n-1 is needed. I find this is a source of confusion with students.

**Comment by dwsideriusNIST** [comment]
I made a very slight text revision to your footnote, 1) to use our macro for s(x), 2) "an" instead of "and", and 3) clarifying that the true standard deviation of the mean is being underestimated.

**Comment by mangiapasta** [comment]
Looks good.  Thanks

**Comment by dwsideriusNIST** [comment]
Closed.
