### ISSUE TITLE
Bootstrap Section

### ISSUE THREAD

**Issue by dwsideriusNIST** [dmzuckerman/Sampling-Uncertainty#41]
Per reviewer

"Section 7.6 is key, and again I was wanting to see more details - this topic is confusing to students and if the authors could provide more details with an example, it would be great."

NOTE: In email discussion with @mangiapasta, we agreed that this section has to rely on references; to do a full work up of bootstrap/resampling would be a paper by itself.

**Comment by agrossfield** [comment]
I think the reviewer has a point, in that the discussion goes a little quickly.  I think we should add a sentence right near the top, perhaps as the second sentence:

A full discussion of bootstrapping and resampling methods is outside the scope of this article; we will cover the broad strokes here, and suggest interested readers consult excellent discussions elsewhere for more details (e.g. Refs 38 and 39, and particularly Ref 35).

**Comment by mangiapasta** [comment]
Fine by me.  I made the change

**Comment by dwsideriusNIST** [comment]
Closed.
