### ISSUE TITLE
Notation / Definitions

### ISSUE THREAD

**Issue by dwsideriusNIST** [dmzuckerman/Sampling-Uncertainty#44]
Per reviewers:

"p3: In a didactical sense, maybe it would be worth stating (footnote?) that a probability distribution P(x) has units which are inverse of those of x, and that it should be normalized (i.e. integrate to one); "probability" graphs which are not normalized or/and reported in "arbitrary units" or in "percent" are a very common "bad practice", I think"

"p3/footnote 3: "As such, we can only…" I agree that it is not possible to fully characterize a P(x) based on finite sampling. But if you say "estimate", I don't know why you should limit the statement to expectation value and variance (one can "estimate" higher moments as well, and P(x) itself as a histogram approximation)"

"p3: The notation s(x_j) is mathematically unclean (especially for a "best practice" paper), as it suggests that "s" is a function of "x_j". What is meant is more like s({x_j}) or s(xv) where xv is the x_j-vector"

"p3: "which is a stronger condition…" - there is a beautiful counter example (maybe for a footnote?): data that is perfectly aligned on a circle! (perfect correlation, but zero linear correlation)"

**Comment by dwsideriusNIST** [comment]
Commit addresses:
1) units of P(x)
2) estimation of P(x) and its properties

I do not want to edit the definition section to deal with the s(x) versus s(x_j) issue; that note is included only because the VIM & GUM use the s(x_j) notation that we thought clunky and we want to make clear what *we* mean by s(x). We'll include a reply in the response letter.

@mangiapasta can you address the "stronger condition" issue?

**Comment by mangiapasta** [comment]
Yes, I will work on that today.  Won't be before this afternoon though

________________________________

**Comment by dmzuckerman** [comment]
@mangiapasta @dwsideriusNIST @agrossfield 
If someone is willing to start a response letter now, I think that will save us a lot of time and hassle later.  As soon as you make a change, also add that, with explanation, to the response letter while it's fresh in your mind.  The letter will be much more painful to assemble later.
