### ISSUE TITLE
ACF / Block Analysis

### ISSUE THREAD

**Issue by dwsideriusNIST** [dmzuckerman/Sampling-Uncertainty#46]
Per Reviewers:

"p4: At "correlation time", maybe add a footnote for the MC case (as there is no "time" there); later, a footnote 11 says this, but it is a bit late"

"p11/footnotes 14,15: Very often, one encounters TCFs that have a damped-oscillatory form. It is not clear at all to me how to extract a "tau" from these. And the time integral of C(tau) is only expected to deliver tau if C(tau) is exponential. What if it is not? Finally, if I agree that the effective number of sample is proportional to N_config/tau, is the appropriate prefactor really one? (I have never worked out the math, but I am sure this has been done)"

"p16/footnote 16: This footnote is unclear to me. Seems to me the blocks are non-overlapping and tiling segments of the entire time series (the possibility that it may be otherwise was never mentioned in the text; and I don't think anyone would do this in practice"

**Comment by dwsideriusNIST** [comment]
Please take a look at revisions on page 4 and 16 to deal with the correlation time and the block size issue.

My footnote about the block average not equaling the trajectory average was included due to personal experience. Say there are 10^6 observations; the first blocking operation uses a block size of 5^5 and does not discard data. The second block operation divides the sequence into three blocks, using 3.\bar{3}^5 observations, discarding one. Then the average of the block averages has to differ from the trajectory average. This happens any time mod(length,block size) /= 0. Sorry to be pedantic, but this is entirely glossed over in the standard text references.

**Comment by mangiapasta** [comment]
So regarding the question about p11 and footnotes 14 and 15, I think there are some ambiguities we need to clear up.  

1) I think the reviewer is thinking of a correlation time like C(t-t') ~ exp[-|t-t'|/tau], where tau is the correlation time.  
2) I don't think we mean the same think; namely correlation time as we define it is the tau for which t>tau => C(t) = 0 to within uncertainty
3) So, in Eq. 12, for example, shouldn't N_lags really be replaced with tau?
4) Is it fair to say that tau can be obtained by inspection?

**Comment by dwsideriusNIST** [comment]
In reply to @mangiapasta:

1, 2: I agree that the reviewer is conflating two concepts, so we can just brush this comment aside
3: No, the "N_lags" in eq. 12 is correct; the summation is over the C_j where j identifies a specific lag. The sum variable was incorrect (i vs. j) and I've corrected that in the most recent commit.
4: Yes, we could say that tau can be obtained by inspection, but I am in favor of a recipe that is more reproducible.

**Comment by mangiapasta** [comment]
On point 3, I'm confused though.  If we take definition 2 as our meaning of correlation time, then shouldn't C_j=0 for j > tau?  So a bunch of terms in that sum are zero. I guess there is no harm in using N_lags, but it's not as precise.

**Comment by mangiapasta** [comment]
Alternatively, leaving N_lags gets around the problem of having to actually compute tau.  Admittedly I think we only introduce the latter concept as a heuristic tool to understand correlation, not as a necessary computational tool.  Is that correct?

**Comment by dwsideriusNIST** [comment]
OK, I see my mistake in interpretation. We have
1) a hard definition of tau, e.g. the time for which <x(t+tau)x(t)> = 0
2) the N^{ind} definition in eq 12, which doesn't directly reference tau

I'll admit that I've seen competing definitions of N^{ind} in terms of all of the lags (our version 12) and in terms of just the "correlated" region of the ACF.
But then there is the question "what about lags \tau2 > \tau where <x(t+tau2)x(t)> /= 0? E.g., the damped-oscillatory ACF that we often encounter in simulations. Or the fact that there are multiple "\tau" where the non-correlation condition holds? Especially if there is a large amplitude oscillation "after" the first (or second, etc.) tau that satisfies the condition.

So, regarding your most recent comment, I agree that tau is introduced as a heuristic, but that I would not encourage its use as a quantitative metric. The summation over all lags is less ambiguous and better suited to a "recipe" approach that removes some subjectivity.

**Comment by mangiapasta** [comment]
Okay I think we're more or less in agreement.

As regards the oscillatory correlations, I think that's actually already accounted for in our definition because it is stated in terms an open set of times extending to infinity, not individual times.

That is, tau is the time for which C(t) = 0 *for all t > tau*.

**Comment by mangiapasta** [comment]
I think that's why it can essentially be estimated by inspection.  So I would actually rewrite your definition 1 to include "for all t > tau."  

The more I think about it, there is a hidden danger in using N_lags.  Specifically, if there is noise in the correlation function, there is a good chance it may be (or at least look like) white noise.  Thus, if you integrate over all lags, and C -> 0 for some t << N_lags, you're adding up a bunch of white noise, which amounts to adding a Browning motion to your computation of N_ind....

**Comment by dwsideriusNIST** [comment]
Yes, I agree that were in essential agreement.

This is, perhaps, where my inner engineer comes through. C(t) = 0 _for all t > tau_ may not exist, so is the correlation time infinite? For practical reasons, though, the sum definition yields a reasonable estimation of the number of independent samples.

**Comment by mangiapasta** [comment]
I saw this exact problem bite someone pretty badly just last week.  It happens in the case of integrating autocorrelation functions associated with viscosity calculations.  The integral converges for a while and then begins to diverge, precisely because one is integrating noise as soon as the signal dies down too much.

**Comment by mangiapasta** [comment]
Yes, in that case the correlation time is infinite.  That's not to say it can't be integrated, or even asymptotically approximated, which is what the sum definition is doing.

**Comment by dwsideriusNIST** [comment]
I've encountered the same issue in obtaining viscosity / diffusivity from an ACF. We put a hard bound on the summation when using that technique.

But isn't that partially related to the fact that a moment of the ACF is used? Whereas for computing N^{ind}, we just summing the ACF, so any white noise should cancel itself out.

**Comment by mangiapasta** [comment]
I guess the problem I'm thinking about is that N_lags actually needs to be only those lags over which the signal-to-noise ratio of the correlation function is significant, i.e. at least O(1) and maybe larger

**Comment by mangiapasta** [comment]
No, noise does not cancel, only in the average.  But realizations will give you a Brownian motion

**Comment by mangiapasta** [comment]
Sorry, let me be clearer, individual realizations of integrating noise are realizations of a brownian motion.  Brownian motion is only zero on averaging between realizations.  Individual brownian motions are effectively never zero

**Comment by dwsideriusNIST** [comment]
So... what is the best approach here for providing a "way to do this"? The readers want clear instructions, which requires some sort of unambiguous recipe.

**Comment by mangiapasta** [comment]
Yeah, I'm struggling with that question myself.  I'm leaning towards saying one needs to find estimate tau if it is finite or use N_lags is the correlation function does not devolve to noise.  But as far as I can tell, there is not a clear "winner" that the community has adopted.  I don't think the community has even really tried to address this problem clearly, have they?  I only started thinking about it a year ago, and even they I often estimate tau by inspection.  

I know that there are more advanced methods based on stochastic regression that attempt to pull the noise out, but that's active research / way beyond our audience.  Should we ask the other authors?

**Comment by mangiapasta** [comment]
@dmzuckerman 

I think what you suggest is a level-headed approach.  @dwsideriusNIST I can take a crack at this if you want.  Also happy to wait and entertain other opinions first.

**Comment by agrossfield** [comment]
I agree with @dmzuckerman as well.  

As for implementing in LOOS, :-)

**Comment by dwsideriusNIST** [comment]
@mangiapasta go ahead with a rewrite.

My main concern here is that we don't hamstring a particular approach by presenting perfectly impractical theory. Sorry, I'm an engineer at heart.

**Comment by mangiapasta** [comment]
No problem.  Trust me, I understand your perspective on this.  I just want to make sure that people are aware of the pitfalls of integrating noise out to infinity because those pitfalls rear their heads in many real-world settings.  I myself have been caught off guard by this very point despite having a background in stochastic differential equations!  I'll try to thread this needle delicately.

**Comment by mangiapasta** [comment]
Okay I took a first crack at the revision.  I added a small paragraph at teh end of the ACF subsection contained in Section 7.  I also modified the definition of correlation time.  Feel free to edit as appropriate.

**Comment by dwsideriusNIST** [comment]
@mangiapasta I'm happy with the changes you made.
