### ISSUE TITLE
Figures - need reference/permission or credit

### ISSUE THREAD

**Issue by dmzuckerman** [dmzuckerman/Sampling-Uncertainty#5]
Any figure/data shown should have a reference if it's published (in which case we need to get permission for it - I will find out more about this).  If it's not published just put in a ref to yourself - e.g., [P Patrone, unpublished].

**Comment by mangiapasta** [comment]
What information needs to be provided if the figure is published but not subject to copyright (e.g. if someone is a Fed)?  The figure I put in falls under that category

**Comment by dwsideriusNIST** [comment]
Paul: 1) which journal was the figure published in? 2) were *all* of the authors Feds? We can contact the WERB chair.

**Comment by mangiapasta** [comment]
For the figure I uploaded, I was the only author (and a fed at the time).  It was published in the CAMX 2016 Conference Proceedings.

________________________________

**Comment by dwsideriusNIST** [comment]
I checked the WERB FAQ, it's easy: put the citation in the caption, then add "Reprinted courtesy of the National Institute of Standards and Technology, U.S. Department of Commerce. Not copyrightable in the United States."

**Comment by mangiapasta** [comment]
Great, thanks!

________________________________
